## Preprocesamiento de la data

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [2]:
import pandas as pd
import importlib

from src import load
from src import feature_engineering

In [3]:
importlib.reload(load)
importlib.reload(feature_engineering)

In [4]:
anios=range(2022,2027)

In [5]:
datasets_anuales=[]
for i in anios:
    indicadores=load.procesar_indicadores(i, load.archivos,load.meses, load.columnas_indicadores)
    lista_cartera=load.procesar_cartera(i, load.archivos,load.meses)
    indicadores_cartera=feature_engineering.feature_engineering_cartera(lista_cartera)
    lista_indicadores_y_cartera=feature_engineering.unir_todos_indicadores(indicadores, indicadores_cartera)
    indicadores_y_cartera=pd.concat(lista_indicadores_y_cartera,
        ignore_index=True)
    datasets_anuales.append(indicadores_y_cartera)

In [6]:
dataset_indicadores_cartera = pd.concat(
    datasets_anuales,
    ignore_index=True
)

In [7]:
dataset_indicadores_cartera

,MES,AÑO,ENTIDAD,( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6),INDICE DE CAPITALIZACION NETO: FK / FI,ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS,ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO,MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO,MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO,...,GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3),RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO,RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO,CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO),FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO,CARTERA IMPRODUCTIVA / CARTERA BRUTA,CARTERA VENCIDA / CARTERA BRUTA,CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA,CARTERA REFINANCIADA / CARTERA BRUTA,CARTERA REESTRUCTURADA / CARTERA BRUTA
0,Enero,2022,BP GUAYAQUIL,4.141498,0.084334,0.14544,0.85456,1.20628,0.01425,0.022054,...,0.015297,0.128519,0.012238,0.880435,0.21366,0.012428,0.005401,0.007027,0.015168,0.004739
1,Enero,2022,BP PACIFICO,2.6451,0.097085,0.223376,0.77662,1.10437,0.032261,0.034234,...,0.009043,0.102842,0.012095,0.854694,0.341741,0.031243,0.015333,0.015910,0.109175,0.039099
2,Enero,2022,BP PICHINCHA,-23.726736,0.092786,0.093155,0.90684,1.43429,0.032347,0.045745,...,0.011048,0.113642,0.011441,0.830851,0.178394,0.028914,0.007745,0.021169,0.029904,0.055667
3,Enero,2022,BP PRODUBANCO,3.21609,0.0715,0.144305,0.85569,1.43589,0.032538,0.032279,...,0.010637,0.127418,0.010326,0.86819,0.320233,0.015483,0.003208,0.012275,0.007283,0.026373
4,Enero,2022,BP AUSTRO,1.391251,0.078349,0.167015,0.83298,1.05067,0.073443,0.016077,...,0.010616,0.035847,0.003303,0.671742,0.250919,0.039514,0.014388,0.025126,0.079909,0.026752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,Julio,2026,BP CAPITAL,0.743608,0.088779,0.203118,0.796882,0.974991,0.035269,0,...,0.022017,0.000602,0.00008,0.762553,0.241408,0.043296,0.002111,0.041185,0.014315,0.002475
1300,Julio,2026,BP DELBANK,7.435204,0.288765,0.157979,0.842021,1.769811,0.105913,0.000002,...,0.040853,-0.003508,-0.001117,1.275196,0.591112,0.031132,0.010960,0.020171,0.068912,0.003849
1301,Julio,2026,BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.,0.788369,0.055191,0.128191,0.871809,0.96599,0.000358,0,...,0.030823,0.00906,0.000702,0.535486,0.331037,0.021523,0.009165,0.012358,0.028839,0.007510
1302,Julio,2026,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",2.990621,0.103658,0.105249,0.894751,1.069191,0.079619,0.006083,...,0.021339,0.024556,0.0029,0.954322,0.17721,0.099170,0.040266,0.058904,0.041134,0.006622
1303,Julio,2026,BP VISIONFUND ECUADOR S.A.,21.25641,0.128662,0.037131,0.962869,1.177842,0.008478,0,...,0.04589,0.244274,0.034437,2.064977,0.426914,0.044672,0.022074,0.022598,0.007556,0.000656

In [8]:
dataset_indicadores_cartera["ENTIDAD"].unique()

array(['BP GUAYAQUIL', 'BP PACIFICO', 'BP PICHINCHA', 'BP PRODUBANCO',
       'BP AUSTRO', 'BP BOLIVARIANO', 'BP CITIBANK', 'BP DINERS',
       'BP GENERAL RUMIÑAHUI', 'BP INTERNACIONAL', 'BP LOJA',
       'BP MACHALA', 'BP SOLIDARIO', 'BP PROCREDIT', 'BP AMAZONAS',
       'BP BANCO COMERCIAL DE MANABI', 'BP LITORAL', 'BP COOPNACIONAL',
       'BP CAPITAL', 'BP FINCA S.A./BANCO AMIBANK S.A.', 'BP DELBANK',
       'BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.',
       'BP BANCO  DESARROLLO DE LOS PUEBLOS  S.A., CODESARROLLO',
       'BP VISIONFUND ECUADOR S.A.'], dtype=object)

In [9]:
dataset_indicadores_cartera[dataset_indicadores_cartera["ENTIDAD"]=="BANCO AMIBANK S.A., EN LIQUIDACION"]

Empty DataFrame
Columns: [MES, AÑO, ENTIDAD, ( PATRIMONIO + RESULTADOS ) / ACTIVOS INMOVILIZADOS NETOS (3) (6), INDICE DE CAPITALIZACION NETO: FK / FI, ACTIVOS IMPRODUCTIVOS NETOS / TOTAL ACTIVOS, ACTIVOS PRODUCTIVOS / TOTAL ACTIVOS, ACTIVOS PRODUCTIVOS / PASIVOS CON COSTO, MOROSIDAD DE LA CARTERA DE CREDITOS CONSUMO, MOROSIDAD DE LA CARTERA DE CRÉDITOS INMOBILIARIO, MOROSIDAD DE LA CARTERA DE CRÉDITOS MICROCRÉDITO, MOROSIDAD DE LA CARTERA TOTAL, COBERTURA DE LA CARTERA REFINANCIADA, COBERTURA DE LA CARTERA REESTRUCTURADA, COBERTURA DE LA CARTERA PROBLEMÁTICA, GASTOS DE OPERACION ESTIMADOS / TOTAL ACTIVO PROMEDIO (3), GASTOS DE OPERACION  / MARGEN FINANCIERO, GASTOS DE PERSONAL ESTIMADOS / ACTIVO PROMEDIO (3), RESULTADOS DEL EJERCICIO / PATRIMONIO PROMEDIO, RESULTADOS DEL EJERCICIO / ACTIVO PROMEDIO, CARTERA BRUTA / (DEPOSITOS A LA VISTA + DEPOSITOS A PLAZO), FONDOS DISPONIBLES / TOTAL DEPOSITOS A CORTO PLAZO, CARTERA IMPRODUCTIVA / CARTERA BRUTA, CARTERA VENCIDA / CARTERA BRUTA, CARTERA QUE NO DEVENGA INTERESES / CARTERA BRUTA, CARTERA REFINANCIADA / CARTERA BRUTA, CARTERA REESTRUCTURADA / CARTERA BRUTA]
Index: []

[0 rows x 27 columns]

In [16]:
lista_balance=load.procesar_balances(load.archivos,load.meses, load.cuentas)
indicadores_balance=feature_engineering.calcular_variaciones_balance(lista_balance)

In [17]:
indicadores_balance.columns.to_list()

['MES',
 'AÑO',
 'ENTIDAD',
 'VAR_FONDOS DISPONIBLES',
 'VAR_INVERSIONES',
 'VAR_CARTERA DE CRÉDITOS',
 'VAR_TOTAL ACTIVO',
 'VAR_Depósitos a la vista',
 'VAR_Depósitos a plazo',
 'VAR_TOTAL PATRIMONIO']

In [18]:
indicadores_balance

,MES,AÑO,ENTIDAD,VAR_FONDOS DISPONIBLES,VAR_INVERSIONES,VAR_CARTERA DE CRÉDITOS,VAR_TOTAL ACTIVO,VAR_Depósitos a la vista,VAR_Depósitos a plazo,VAR_TOTAL PATRIMONIO
0,Mayo,2022,BP GUAYAQUIL,-0.181440,-0.032054,0.180083,0.097880,0.126022,0.140413,0.074825
1,Mayo,2022,BP PACIFICO,-0.191929,0.132052,-0.006760,-0.002162,-0.038956,0.070775,0.019641
2,Mayo,2022,BP PICHINCHA,-0.528962,0.008815,0.254786,0.096528,0.083374,0.150097,0.041933
3,Mayo,2022,BP PRODUBANCO,-0.047137,-0.036503,0.194524,0.121316,0.085067,0.106794,0.072333
4,Mayo,2022,BP AUSTRO,-0.189596,0.064650,0.176344,0.102339,0.072555,0.045989,0.113580
...,...,...,...,...,...,...,...,...,...,...
1203,Julio,2026,BP CAPITAL,-0.017959,0.352889,0.302676,0.243820,0.044237,0.308268,0.039135
1204,Julio,2026,BP DELBANK,0.087778,-0.610968,-0.135040,-0.114138,-0.143412,-0.293775,0.049285
1205,Julio,2026,BP D-MIRO S.A./BANCO ATLÁNTIDA S.A.,0.583142,0.337332,0.438530,0.416208,0.215761,0.523101,-0.059867
1206,Julio,2026,"BP BANCO DESARROLLO DE LOS PUEBLOS S.A., COD...",-1.415287,0.199139,0.035629,-0.054711,-0.160610,0.079677,0.062820
1207,Julio,2026,BP VISIONFUND ECUADOR S.A.,0.103111,0.401001,0.188952,0.188327,0.310567,0.413123,0.072721

In [19]:
dataset_final = dataset_indicadores_cartera.merge(
    indicadores_balance,
    on=["MES", "AÑO", "ENTIDAD"],
    how="left"
)

In [20]:
dataset_final.to_excel(
    "dataset_final.xlsx",
    index=False
)